normal_train:
    train_data_path: data/train.txt
    valid_data_path: data/valid.txt
    test_data_path: data/test.txt
    epochs: 50
    early_stopping: 5 # == 0 or False: Disable, > 0: Trigger

params_search:
    train_data_path: data/train4search.txt
    valid_data_path: data/valid4search.txt
    epochs: 50
    trials: 200
    early_stopping: 5 # == 0 or False: Disable, > 0: Trigger

common:
    batch_size: 64
    model_cache_path: .model_cache
    measure: p@1 # micro-f1, macro-f1, p@1, p@3 or p@5
    sequence_length: 500

hyper_params:
    d_max_pool_p: [125, 128, 128]
    filter_channels: 128
    filter_sizes: [2, 4, 8]
    hidden_dims: 512
    learning_rate: 0.0005099137446356937
    stride: [2, 1, 1]
